apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /api/v1/test
        pathType: ImplementationSpecific
        backend:
          service:
            name: hellov1
            port:
              number: 80
      - path: /api/v1/catalog
        pathType: ImplementationSpecific
        backend:
          service:
            name: catalog
            port:
              number: 80
      - path: /api/v1/customer
        pathType: ImplementationSpecific
        backend:
          service:
            name: customer
            port:
              number: 80
      - path: /api/v1/order
        pathType: ImplementationSpecific
        backend:
          service:
            name: order
            port:
              number: 80

